### ISSUE TITLE
Refatorar o código

### ISSUE THREAD

**Issue by marcoshsbosco** [marcoshsbosco/Forca#5]
Refatorar tudo em termos de legibilidade.
- Colocar nomes de variável decentes
- Comentar onde não tá comentado
- Consertar comentários bostas

**Comment by mariaalm20** [comment]
- Colocar assinatura em todos os métodos
- Colocar alguns testes unitários

**Comment by marcoshsbosco** [comment]
Tudo feito, só não sei se tá bom de teste porque só tem um, que é o do `troca-acento`.
